branch-defaults:
  default:
    environment: image-project-dev
deploy:
  artifact: /home/workspace/cd12099-Full-Stack-Apps-AWS/projectstartercode/www/Archive.zip
global:
  application_name: image-project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
